### ISSUE TITLE
OnCreate is not called on every ViewModel

### ISSUE THREAD

**Issue by sdoward** [alter-ego/androidbound#163]
Steps to reproduce

- Set `contentView(R.id.foo, BarViewModel)` in `Activity.onCreate()`
- AddViewModel with `addViewModel(R.layout.foo1, Bar1ViewModel, ID)` in `Activity.onCreate()`

**Expected behaviour:**  The `onCreate()` method on **both** ViewModels is called

**Observed behaviour:** `onCreate()` method is only called on the first ViewModel that is added

**Comment by mrsasha** [comment]
fixed in 0.9.1
